services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bot
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
